name: my application


on : 
    pull_request:
        branches:
            - main
    push:
        branches:
            - main
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: chcekout code
              uses: actions/checkout@v2
            
            - name: Set up node 
              uses: actions/setup-node@v3
              with:
                node-version: '14' 
            - name: install dependencies
              run: npm install
            - name: Run tests
              run: npm test
    docker:
        needs: build
        runs-on: ubuntu-latest
        steps:
            - name: chcekout code
              uses: actions/checkout@v2
            - name: login to DockerHub
              uses: docker/login-action@v2
              with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PASSWORD }}
            
    update-deployment:
        needs: docker
        runs-on: ubuntu-latest
        steps:
            - name: chcekout code
              uses: actions/checkout@v2 
              with:
                token: ${{ secrets.GITHUB_TOKEN }}

            
            - name: git commit
              run: |
                git config --global user.name 'vinodmidathala'
                git config --global user.email 'mvk4459@gmail.com'
                git add .
                git commit -m 'Update mongo'
                git push origin main        

     