name: my application


on : 
    pull_request:
        branches:
            - main
    push:
        branches:
            - main
jobs:

    update-deployment:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
            - name: git commit
              run: |
                git config --global user.name 'vinodmidathala'
                git config --global user.email 'mvk4459@gmail.com'
                git add .
                git commit -m 'Update mongo'
                git push origin main        

     